gpu: [0]

# directories
dataset_dir: !Path '../data_10.06.p01' # folder containing root files

# geometry
detector:
  xlim: [-250, 250] # x boundaries in mm
  ylim: [-250, 250] # y boundaries in mm
  zlim: [-250, 250] # z boundaries in mm
  resolution: [5, 5, 1] # [x, y, z] resolution in mm
  min_energy: 0.1 # energy sensitivity in MeV

model:
  attention:
    ckpt: null # checkpoint, must be !Path object too
    optimizer: Adam
    lr: 1e-3 # learning rate
    epochs: 10
    # hist_freq: 10
    min_lr: 1e-6 # minimum lr
    reducelr_patience: 20 # reduce lr on plateau patience
    es_patience: 100 # early stopping patience
    net_dict:
      f_dims: 4
      spatial_dims: 3
      nb_mha_heads: 4
      mha_filters: [8, 64, 128]
      nb_fc_heads: 1
      fc_filters: [64, 16, 2]
      batch_size: 32
      activation: relu
      alpha: 0.2
      dropout_rate: 0.0
      use_bias: true
      name: AttentionNetwork
  cnn:
    lr: 0.001 # learning rate
    epochs: 25
    feature_number: 4 # Intermediate dense layer size (the features for SVM)
    batch_size: 120
    alpha: 0.05
    dropout_rate: 0.25
    val_te_ratio: 0.15 # % of the total dataset (validation and test have the same size)
    name: CNN
  svm:
    extrafeats: False # If True: feature space includes (ntot, etot)
    name: SVM
    